## Numpy 

Numpy는 Numerical Python의 줄임말로, 파이썬에서 산술 계산을 위한 가장 중요한 패키지 중 하나입니다. 과학 계산을 위한 대부분의 패키지는 Numpy의 배열 객체를 데이터 교환을 위한 공통 언어처럼 사용합니다.

### Numpy 라이브러리 import

In [77]:
import numpy as np

### Numpy ndarray

Numpy의 핵심 기능 중 하나는 ndarray라고 하는 N차원의 배열 객체인데 파이썬에서 할 수 있는 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료구조입니다.

In [78]:
a = np.array([1, 2, 3])
print(a, type(a))

b = np.array([1, 2, 3.])
print(b, type(b))

[1 2 3] <class 'numpy.ndarray'>
[1. 2. 3.] <class 'numpy.ndarray'>


### List와 비교

In [79]:
L = [1, 2, 3]
A = np.array([1, 2, 3])

print(f'L: {L}')
print(f'A: {A}')


L: [1, 2, 3]
A: [1 2 3]


In [80]:
for item in L:
    print(item)

1
2
3


In [81]:
for item in A:
    print(item)

1
2
3


In [82]:
L.append(4)
print(L)

[1, 2, 3, 4]


In [83]:
# A.append(4) # 지원하지 않음
# print(A)

In [84]:
A = np.append(A, 4)
print(A)

[1 2 3 4]


In [85]:
L = L + [5]
print(L)

[1, 2, 3, 4, 5]


In [86]:
A = A + np.array([5]) # 브로드케스팅
print(A)

[6 7 8 9]


In [87]:
# list의 모든 원소를 2배로 만들기 

L = [1, 2, 3]
L2 = []
L3 = L * 2
for item in L:
    L2.append(item * 2)
print(L2)
print(L3)


[2, 4, 6]
[1, 2, 3, 1, 2, 3]


In [88]:
A = np.array(L)
A2 = A * 2
print(A2)

[2 4 6]


### 배열 

numpy 배열은 모두 같은 유형의 값이며 음수가 아닌 정수의 튜플로 인덱싱됩니다. 차원의 수는 배열의 랭크입니다. 배열의 shape은 각 차원별 배열 크기의 튜플입니다. 중첩된 파이썬 리스트로부터 numpy배열을 초기화 할 수 있고 대괄호를 사용하여 요소에 접근 할 수 있습니다.

### 배열 생성하기

In [89]:
a = np.array([1, 2, 3])
print(a)
print(type(a), a.ndim, a.shape, a.dtype)

# a.ndim = 1 (1차원)
# a.shape = (3,) (3개의 원소를 가지고 있음(각 차원별 배열의 크기(튜플형태)))
# a.dtype = int32 (원소의 타입) 


[1 2 3]
<class 'numpy.ndarray'> 1 (3,) int64


In [90]:
b = np.asarray(a) # a를 복사해서 b를 만듦 (둘이 연결되 있어 b를 바꾸면 a도 바뀜)
print(b)

[1 2 3]


In [91]:
b[0] = 9 # (둘이 연결되 있어 b를 바꾸면 a도 바뀜)
print(a)
print(b)

[9 2 3]
[9 2 3]


In [92]:
c = np.array(a) # a를 복사해 c를 만들지만 둘이 연결되어있지 않음
print(c)

[9 2 3]


In [93]:
c[0] = 1 # 따라서 a는 바뀌지 않음
print(a)
print(b)
print(c)

[9 2 3]
[9 2 3]
[1 2 3]


In [94]:
a = np.zeros((3,4)) # 3행 4열의 0으로 채워진 배열
print(a)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [95]:
b = np.ones((5, 2)) # 5행 2열의 1로 채워진 배열
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]


In [96]:
c = np.full((2,3), 4)   # 2행 3열의 4로 채워진 배열
print(c)

[[4 4 4]
 [4 4 4]]


In [97]:
d = np.empty((3,3)) # 3행 3열의 빈 배열
print(d)

[[6.17779239e-31 1.23555848e-30 3.08889620e-31]
 [1.23555848e-30 2.68733969e-30 8.34001973e-31]
 [3.08889620e-31 8.34001973e-31 4.78778910e-31]]


In [99]:
e = np.zeros_like(a) # a와 같은 행렬 크기의 0으로 채워진 배열
f = np.ones_like(a) # a와 같은 행렬 크기의 1로 채워진 배열
g = np.full_like(a, 5) # a와 같은 행렬 크기의 5로 채워진 배열
h = np.empty_like(a) # a와 같은 행렬 크기의 빈 배열

print(e)
print(f)
print(g)
print(h)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]
[[5. 5. 5. 5.]
 [5. 5. 5. 5.]
 [5. 5. 5. 5.]]


In [100]:
i = np.eye(3) # 3행 3열의 단위행렬
j = np.identity(3) # 3행 3열의 단위행렬
print(i)
print(j)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [110]:
k = np.arange(10) # 0부터 9까지의 배열
print(k)

k = np.arange(1, 11) # 1부터 10까지의 배열 (이상, 미만)
print(k)

k = np.arange(10, 0, -1) # 10부터 1까지의 배열
print(k)

[0 1 2 3 4 5 6 7 8 9]
[ 1  2  3  4  5  6  7  8  9 10]
[10  9  8  7  6  5  4  3  2  1]


In [115]:
# uniform distribution (모두가 똑같은 확률)

l = np.random.rand(2, 2) # 2행 2열의 0~1 사이의 랜덤한 배열
print(l)

[[0.58483088 0.62799737]
 [0.89094383 0.03225121]]


In [116]:
# normal distribution (표준 정규분포)
m = np.random.randn(2, 2) # 표준이 0이고 표준편차가 1인 정규분포
print(m) 

[[-0.82473604 -0.11128746]
 [ 0.0237374   1.222657  ]]


### 배열의 dtype

In [117]:
a = np.array([1, 2, 3])
b = np.array([1, 2, 3], dtype=np.float64)
c = np.array([1, 2, 3], dtype=np.int32)

print(a.dtype, b.dtype, c.dtype)

int64 float64 int32


In [118]:
d = np.array([1, 2, 3], dtype='i1') # int8
e = np.array([1, 2, 3], dtype='i2') # int16
f = np.array([1, 2, 3], dtype='i4') # int32
g = np.array([1, 2, 3], dtype='i8') # int64

print(d.dtype, e.dtype, f.dtype, g.dtype)

int8 int16 int32 int64


In [119]:
d = np.array([1, 2, 3], dtype='u1') # uint8
e = np.array([1, 2, 3], dtype='u2') # uint16
f = np.array([1, 2, 3], dtype='u4') # uint32
g = np.array([1, 2, 3], dtype='u8') # uint64

print(d.dtype, e.dtype, f.dtype, g.dtype)

uint8 uint16 uint32 uint64


In [122]:
h = np.array([1, 2, 3], dtype='f2') # float16
i = np.array([1, 2, 3], dtype='f4') # float32
j = np.array([1, 2, 3], dtype='f8') # float64
# k = np.array([1, 2, 3], dtype='f16') # float128

# print(h.dtype, i.dtype, j.dtype, k.dtype)
print(h.dtype, i.dtype, j.dtype)


float16 float32 float64


In [123]:
i = np.array([1, 2, 3], dtype='f') # float32
j = np.array([1, 2, 3], dtype='d') # float64
k = np.array([1, 2, 3], dtype='g') # float128

print(i.dtype, j.dtype, k.dtype)

float32 float64 float64


In [124]:
i = i.astype(np.int32) # i의 타입을 int32로 바꿈
print(i.dtype)

int32


In [126]:
j = j.astype(i.dtype) # j의 타입을 i의 타입으로 바꿈
print(j.dtype)

int32
