### Numpy 연산  

In [54]:
import numpy as np

In [55]:
x = np.array([[1, 2], [3, 4]], dtype = np.float64)
y = np.array([[5, 6], [7, 8]], dtype = np.float64)

print(x)
print(y)

[[1. 2.]
 [3. 4.]]
[[5. 6.]
 [7. 8.]]


In [56]:
print(x + y)
print(np.add(x, y))

[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [57]:
print(x - y)
print(np.subtract(x, y))

[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [58]:
print(x * y)
print(np.multiply(x, y))

[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [59]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [60]:
print(x @ y)
print(np.matmul(x, y)) # matrix multiplication


[[19. 22.]
 [43. 50.]]
[[19. 22.]
 [43. 50.]]


In [61]:
z = np.arange(1, 11).reshape(2, 5)
print(z)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [62]:
print(np.sum(z))

55


In [63]:
sum1 = np.sum(z, axis = 0)
sum2 = np.sum(z, axis = 1)
sum3 = np.sum(z, axis = -1)

print(sum1, sum1.shape)
print(sum2, sum2.shape)
print(sum3, sum3.shape)

[ 7  9 11 13 15] (5,)
[15 40] (2,)
[15 40] (2,)


여기서 축(axis)은 각 배열의 차원에 해당되는 index 입니다.
axis=0에 대하여 sum을 하라는 것은 0번 축 혹은 차원이 없어지는 방향으로 원소들을 모두 더하라는 얘기입니다.
즉, 위 에서 sum1의 경우, z[0,:] + z[1,:] 의 연산을 하라는 의미이고,
sum2의 경우에는 z[:,0] + z[:,1] + z[:,2] + z[:,3] + z[:,4] 의 연산을 하라는 의미입니다.

z[행, :] = 행을 고정하고 열을 다 더하기
z[:, 열] = 열을 고정하고 행을 다 더하기

쉽게 말하면,
2차원 일 때 axis = 0 의 의미는 위아래로 쭉 더하기
2차원 일 때 axis = 1 또는 -1 의 의미는 같은 행끼리 더하기




In [64]:
z[0,:] + z[1,:]


array([ 7,  9, 11, 13, 15])

In [65]:
z[:,0] + z[:,1] + z[:,2] + z[:,3] + z[:,4]

array([15, 40])

### Broadcasting

Broadcasting은 numpy가 산술 연산을 수행 할 때 다른 모양의 배열로 작업 할 수 있게 해주는 강력한 메커니즘입니다. 종종 더 작은 배열과 더 큰 배열이 있을 때 더 작은 배열을 여러번 사용하여 더 큰 배열에서 어떤 연산을 수행하기를 원할 때가 있습니다. 

예를 들어, 행렬의 각 행에 상수 벡털르 추가하려 한다고 가정합시다. numpy에서는 다음과 같이 할 수 있습니다.

In [66]:
x = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12]])
y = np.array([1, 0, 2])

In [67]:
print(x, x.shape)
print()
print(y, y.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)

[1 0 2] (3,)


In [68]:
z = x + y
print(z, z.shape)

[[ 2  2  5]
 [ 5  5  8]
 [ 8  8 11]
 [11 11 14]] (4, 3)


- 두 행렬의 행의 갯수가 다를 때 1인 행이 존재 한다면 이 행을 늘려서 연산을 수행한다.

In [69]:
x = np.array([1,2,3]).reshape(1, 3)
y = np.array([4,5]).reshape(1, 2)  

print(x, x.shape)
# print(x + y)    #  x와 y의 열의 갯수가 틀리므로 에러 발생

[[1 2 3]] (1, 3)


In [70]:
y = y.swapaxes(0, 1)
print(y, y.shape)
print(x + y)    #  x와 y의 열의 갯수가 같으므로 에러 발생하지 않음



[[4]
 [5]] (2, 1)
[[5 6 7]
 [6 7 8]]


### Shape 변경

In [71]:
a = np.arange(24).reshape(2, 3, 4)
print(a, a.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] (2, 3, 4)


In [72]:
a = a.reshape(4, -1)
print(a, a.shape)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]] (4, 6)


In [73]:
a = a[..., np.newaxis]
print(a, a.shape)

[[[ 0]
  [ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]
  [11]]

 [[12]
  [13]
  [14]
  [15]
  [16]
  [17]]

 [[18]
  [19]
  [20]
  [21]
  [22]
  [23]]] (4, 6, 1)


In [74]:
a = a.reshape(4, 6)
a = np.expand_dims(a, axis = 0)
print(a, a.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [75]:
b = a.copy()
print(b, b.shape)

[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (1, 4, 6)


In [76]:
c = np.concatenate((a, b), axis = -1)
print(c, c.shape)

[[[ 0  1  2  3  4  5  0  1  2  3  4  5]
  [ 6  7  8  9 10 11  6  7  8  9 10 11]
  [12 13 14 15 16 17 12 13 14 15 16 17]
  [18 19 20 21 22 23 18 19 20 21 22 23]]] (1, 4, 12)


In [77]:
d = np.concatenate((a, b), axis = 0)
print(d, d.shape)


[[[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]

 [[ 0  1  2  3  4  5]
  [ 6  7  8  9 10 11]
  [12 13 14 15 16 17]
  [18 19 20 21 22 23]]] (2, 4, 6)


In [78]:
d = np.stack((a, b), axis = -1)
print(d, d.shape)

[[[[ 0  0]
   [ 1  1]
   [ 2  2]
   [ 3  3]
   [ 4  4]
   [ 5  5]]

  [[ 6  6]
   [ 7  7]
   [ 8  8]
   [ 9  9]
   [10 10]
   [11 11]]

  [[12 12]
   [13 13]
   [14 14]
   [15 15]
   [16 16]
   [17 17]]

  [[18 18]
   [19 19]
   [20 20]
   [21 21]
   [22 22]
   [23 23]]]] (1, 4, 6, 2)


In [79]:
d = np.stack((a, b), axis = 0)
print(d, d.shape)

[[[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]


 [[[ 0  1  2  3  4  5]
   [ 6  7  8  9 10 11]
   [12 13 14 15 16 17]
   [18 19 20 21 22 23]]]] (2, 1, 4, 6)
