### 배열 indexing(색인)과 slicing

In [32]:
import numpy as np

indexing, slicing 기본

In [33]:
a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [34]:
# indexing
print(a[5])

5


In [35]:
# slicing
print(a[5:8])

[5 6 7]


In [36]:
print(a[-1])

9


In [37]:
print(a[7:-1])

[7 8]


In [38]:
a[5:8] = 10
print(a)

[ 0  1  2  3  4 10 10 10  8  9]


### indexing과 slicing의 차이

indexing을 사용하면 항상 랭크가 감소합니다. 반면에 slicing을 사용하면 차원이 유지됩니다.

In [39]:
b = np.arange(1, 13)
# b = b.reshape(3, 5)
print(b)
print(b.shape)
print(b.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)
1


In [40]:
indexing = b[1]
slicing = b[1:2]
print(indexing, indexing.shape, indexing.ndim) # 0차원 (차원 감소)
print(slicing, slicing.shape, slicing.ndim)    # 1차원 유지


2 () 0
[2] (1,) 1


이것은 indexing과 slicing을 함께 사용할 때도 마찬가지입니다. indexing의 개수만큼 랭크는 감소합니다.

In [44]:
b = b.reshape(3, 4)
print(b)
print(b.shape)
print(b.ndim)


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
(3, 4)
2


In [47]:
row_r1 = b[0, :]
print(row_r1)

row_r2 = b[1:2, :]
print(row_r2)

print()
print(row_r1, row_r1.shape, row_r1.ndim)
print(row_r2, row_r2.shape, row_r2.ndim)

[1 2 3 4]
[[5 6 7 8]]

[1 2 3 4] (4,) 1
[[5 6 7 8]] (1, 4) 2


slicing examples

In [48]:
c = np.arange(24).reshape(2, 3, 4) # 행렬 2개가 3행 4열 형태로 존재
print(c)
print(c.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)


In [52]:
print(c[:,:,:1])
print("-----------------")
print(c[...,:1])

[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]
-----------------
[[[ 0]
  [ 4]
  [ 8]]

 [[12]
  [16]
  [20]]]


In [53]:
print(c[0:1])
print(c[0::-1]) # 된다는거지 쓰지마셈

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]


boolean indexing

In [54]:
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [55]:
bool_idx = (c > 10)
print(bool_idx)

[[[False False False False]
  [False False False False]
  [False False False  True]]

 [[ True  True  True  True]
  [ True  True  True  True]
  [ True  True  True  True]]]


In [57]:
print(c[bool_idx]) # 무조건 1차원으로 출력

[11 12 13 14 15 16 17 18 19 20 21 22 23]


In [58]:
c[c>10] = -1    # 차원 유지
print(c)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 -1]]

 [[-1 -1 -1 -1]
  [-1 -1 -1 -1]
  [-1 -1 -1 -1]]]


fancy indexing (정수 인덱싱)

In [59]:
d = np.arange(8).reshape(8, -1) # -1은 알아서 계산해라
print(d, d.shape)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]] (8, 1)


In [60]:
d = np.hstack((d, d, d, d)) # horizontal stack
print(d, d.shape)

[[0 0 0 0]
 [1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]
 [5 5 5 5]
 [6 6 6 6]
 [7 7 7 7]] (8, 4)


In [61]:
print(d[[3, 5, 1, 0]])

[[3 3 3 3]
 [5 5 5 5]
 [1 1 1 1]
 [0 0 0 0]]


In [62]:
print(d[[-3, -5, -7]])

[[5 5 5 5]
 [3 3 3 3]
 [1 1 1 1]]


In [64]:
e = np.arange(32).reshape(8, 4)
print(e, e.shape)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] (8, 4)


In [65]:
print(e[[1, 5, 7, 2], [0, 3, 1, 2]]) # 1행 0열, 5행 3열, 7행 1열, 2행 2열 출력

[ 4 23 29 10]


In [66]:
print(e[[1, 5, 7, 2]][:, [0, 3, 1, 2]]) # 각 행에서 0 ,3 ,1 ,2 순서로

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


### Transpose

In [67]:
f = np.arange(16).reshape(2, 2, 4) # 2행 4열 짜리가 2개 (0번축(2) 1번축(2) 2번축(4))
print(f, f.shape)

[[[ 0  1  2  3]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [12 13 14 15]]] (2, 2, 4)


In [68]:
print(f.transpose(1, 0, 2)) # (1번축, 0번축, 2번축) 으로 변경 즉 원래 0번축과 1번축 순서 바꿈

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


In [69]:
print(f.swapaxes(0, 1)) # 0번축과 1번축 순서 바꿈

[[[ 0  1  2  3]
  [ 8  9 10 11]]

 [[ 4  5  6  7]
  [12 13 14 15]]]


tensorflow 에서 이미지 표현 (이미지 세로길이, 이미지 가로길이, 채널수)
pytorch 에서 이미지 표현 (채널수, 이미지 세로길이, 이미지 가로길이)


자세한 내용은 노트 참조