# 5-1: Conv Layers

### Code.5-1-1: Shapes of Conv Layers

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 28, 28, 3
n_filter = 10
f_size = 3

images = tf.random.uniform(minval = 0, maxval = 1,
                           shape = ((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter, kernel_size = f_size)

y = conv(images)

W, B = conv.get_weights()

print(images.shape)  # (1, 28, 28, 1) image 갯수, image 높이, image 넓이, image channel
print(W.shape)       # (3, 3, 3, 10)  filter 높이, filter 넓이, filter channel, filter number
print(B.shape)       # (10, )         bias vector(filter number)

# (n_H - f_size + 1, n_W - f_size + 1)
print(y.shape)       # (1, 26, 26, 10) image 갯수, image 높이, image 넓이, filter number

(1, 28, 28, 3)
(3, 3, 3, 10)
(10,)
(1, 26, 26, 10)


### Code.5-1-2: Correlation Calculation

In [18]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 1
f_size = 3

images = tf.random.uniform(minval = 0, maxval = 1,
                           shape = ((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter, kernel_size = f_size)

y_tf = conv(images)
# print("y(tensorflow):\n", y_tf.numpy())
# print(y_tf.shape)
print("y(tensorflow):\n", y_tf.numpy().squeeze())
# print(y_tf.numpy().squeeze().shape)
W, B = conv.get_weights()

images = images.numpy().squeeze()
W = W.squeeze()

# print(images.shape)
# print(W.shape)
# print(B.shape)

y_man = np.zeros(shape = (n_H - f_size + 1, n_W - f_size + 1))
for i in range(n_H - f_size + 1):
    for j in range(n_W - f_size + 1):
        window = images[i:i+f_size, j:j+f_size, :]
        y_man[i, j] = np.sum(window * W) + B
        
print("Y(Manual):\n", y_man)



y(tensorflow):
 [[0.5807772  0.80894494 0.8066216 ]
 [0.6032288  0.35610676 0.31117508]
 [0.7110289  0.11009558 0.6034144 ]]
Y(Manual):
 [[0.58077717 0.80894494 0.80662167]
 [0.60322887 0.35610676 0.31117505]
 [0.71102881 0.11009555 0.6034143 ]]


# Code.5-2: Conv Layer with Filters

### Code.5-2-1: Shapes with Filters

In [4]:
import tensorflow as tf 
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 32, 28, 28, 3
n_filter = 5
k_size = 3

images = tf.random.uniform(minval = 0, maxval = 1,
                           shape = ((N, n_H, n_W, n_C)))

conv = Conv2D(filters = n_filter, kernel_size = k_size)

Y = conv(images)

W, B = conv.get_weights()

print("Input Image: {}".format(images.shape))    
print("W/B: {} / {}".format(W.shape, B.shape))
print("Output Image: {}".format(Y.shape))

# W/B: (3, 3, 3, 5) / (5,)  filter 높이, filter 넓이, filter channel, filter number

Input Image: (32, 28, 28, 3)
W/B: (3, 3, 3, 5) / (5,)
Output Image: (32, 26, 26, 5)


### Code.5-2-2: Computations with Filters

In [20]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3

n_filter = 3
k_size = 4

images = tf.random.uniform(minval = 0, maxval = 1,
                           shape = ((N, n_H, n_W, n_C)))

# Forward Propagation (Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size)
Y = conv(images)

print(Y.numpy().squeeze(), "\n\n")
# print(Y.shape)
#      1번 filter   2번 filter  3번 filter
# [[[-0.92890024 -0.16372378 -0.5843524 ]
#   [-0.21948192  0.22116992 -1.2751502 ]]

#  [[-0.99914974 -0.04246708 -1.1287332 ]
#   [-0.7139644  -0.41169074 -0.72633725]]] 


# 값이 1인 차원 제거 (1, 2, 2, 3) -> (2, 2, 3) -> (3, 2, 2)
Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print("Y(Tensorflow): \n", Y, Y.shape)

# [[[-0.92890024 -0.21948192]       1번 filter
#   [-0.99914974 -0.7139644 ]]

#  [[-0.16372378  0.22116992]       2번 filter
#   [-0.04246708 -0.41169074]]

#  [[-0.5843524  -1.2751502 ]       3번 filter
#   [-1.1287332  -0.72633725]]]

W, B = conv.get_weights()



# Forward Propagation(Manual)
images = images.numpy().squeeze()

Y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1, n_filter))

for c in range(n_filter):
   c_W = W[:, :, :, c]  # c번째 필터 데이터 가져오기
   c_b = B[c]           # c번째 Bias 값 가져오기
   
   for h in range(n_H - k_size + 1):
      for w in range(n_W - k_size + 1):
         window = images[h: h + k_size, w: w + k_size :]
         conv = np.sum(window * c_W) + c_b
         
         Y_man[h, w, c] = conv
print("\n Y(Manual): \n", np.transpose(Y_man, (2, 0, 1)))



[[[-0.21673033 -0.1711257  -0.9745084 ]
  [-0.2369171  -0.20497946 -0.12059712]]

 [[-0.01200436 -0.2204327  -0.7035195 ]
  [-0.08853148 -0.32026818 -0.59839356]]] 


Y(Tensorflow): 
 [[[-0.21673033 -0.2369171 ]
  [-0.01200436 -0.08853148]]

 [[-0.1711257  -0.20497946]
  [-0.2204327  -0.32026818]]

 [[-0.9745084  -0.12059712]
  [-0.7035195  -0.59839356]]] (3, 2, 2)

 Y(Manual): 
 [[[-0.21673036 -0.23691714]
  [-0.01200438 -0.08853132]]

 [[-0.17112568 -0.20497946]
  [-0.22043265 -0.32026821]]

 [[-0.97450829 -0.1205971 ]
  [-0.70351934 -0.59839362]]]


### np.Transpose

In [24]:
import numpy as np

images = np.random.randint(low = 0, high = 10, size = (2, 3, 4))
                                                    #  0, 1, 2 번째 차원
for c in range(4):
    print(images[:, :, c])
                            # 2번째 차원을 0번째 차원으로 변환
images = np.transpose(images, (2, 0, 1))
                                # 0번째 차원을 1번째로 변환
                                     # 1번째 차원을 2번째로 변환
                                     
print('\n\n', images.shape)

for c in range(4):
    print(images[c, :, :])

[[1 3 7]
 [9 5 0]]
[[3 6 8]
 [6 9 0]]
[[3 2 2]
 [7 9 0]]
[[1 3 2]
 [0 4 1]]


 (4, 2, 3)
[[1 3 7]
 [9 5 0]]
[[3 6 8]
 [6 9 0]]
[[3 2 2]
 [7 9 0]]
[[1 3 2]
 [0 4 1]]


# 5-3: Conv Layers with Activation Functions

In [34]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

N, n_H, n_W, n_C = 1, 5, 5, 3
n_filter = 3
k_size = 4

images = tf.random.uniform(minval = 0, maxval = 1,
                           shape = ((N, n_H, n_W, n_C)))

# Forward Propagation(Tensorflow)
conv = Conv2D(filters = n_filter, kernel_size = k_size, activation = 'sigmoid')
Y = conv(images)
Y = np.transpose(Y.numpy().squeeze(), (2, 0, 1))
print(Y.shape)
print("Y(Tensorflow): \n", Y)
W, B = conv.get_weights()

# Forward Propagation(Manual)
images = images.numpy().squeeze()
print(images.shape)
Y_man = np.zeros(shape = (n_H - k_size + 1, n_W - k_size + 1, n_filter)) # 2, 2, 3

for c in range(n_filter):
    c_W = W[:, :, :, c ]  # filter 높이, filter 넓이, filter channel, filter 갯수
    c_b = B[c]
    
    for h in range(n_H - k_size + 1):
        for w in range(n_W - k_size + 1):
            window = images[h:h + k_size, w:w+k_size, :]
            conv = np.sum(window * c_W) + c_b
            conv = 1 / (1 + np.exp(-conv))

            Y_man[h, w, c] = conv
print("\nY(Manual): \n", np.transpose(Y_man, (2, 0, 1)))
    






(3, 2, 2)
Y(Tensorflow): 
 [[[0.5713987  0.4382515 ]
  [0.6265547  0.5739384 ]]

 [[0.53470564 0.424392  ]
  [0.45841697 0.51780957]]

 [[0.3835066  0.47062007]
  [0.41262174 0.4268586 ]]]
(5, 5, 3)

Y(Manual): 
 [[[0.57139862 0.43825151]
  [0.62655476 0.57393845]]

 [[0.53470565 0.42439197]
  [0.45841698 0.51780957]]

 [[0.38350657 0.47062005]
  [0.41262169 0.42685857]]]


# 5-4: Models with Conv Layers

### Code.5-4-1: Models

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30] # filter 갯수

model = Sequential()
model.add(Conv2D(filters = n_neurons[0], kernel_size = 3, activation = 'relu'))
model.add(Conv2D(filters = n_neurons[1], kernel_size = 3, activation = 'relu'))
model.add(Conv2D(filters = n_neurons[2], kernel_size = 3, activation = 'relu'))

x = tf.random.normal(shape = (32, 28, 28, 3))
predictions = model(x)

print("Input: {}".format(x.shape))
print("Output: {}".format(predictions.shape))

for layer in model.layers:
    W, B = layer.get_weights()
    print("Weights: {}, Biases: {}".format(W.shape, B.shape))
    
print("=============================")
trainable_variables = model.trainable_variables

for train_var in trainable_variables:
    print("Shape: {}".format(train_var.shape) )

Input: (32, 28, 28, 3)
Output: (32, 22, 22, 30)
Weights: (3, 3, 3, 10), Biases: (10,)
Weights: (3, 3, 10, 20), Biases: (20,)
Weights: (3, 3, 20, 30), Biases: (30,)
Shape: (3, 3, 3, 10)
Shape: (10,)
Shape: (3, 3, 10, 20)
Shape: (20,)
Shape: (3, 3, 20, 30)
Shape: (30,)


### Code.5-4-2: Models with Model sub-classing

In [5]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D

n_neurons = [10, 20, 30]

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        global n_neurons
        
        self.conv_layers = []
        for n_neurons in n_neurons:
            self.conv_layers.append(Conv2D(filters = n_neurons, kernel_size = 3, activation = 'relu'))
            
    def __call__(self, x):
        print("Input ", x.shape)
        
        print("\n===== Conv Layers =====\n")
        
        for conv_layer in self.conv_layers:
            x = conv_layer(x)
            W, B = conv_layer.get_weights()
            print("W/B: {}/{}".format(W.shape, B.shape))
            print("X: {}\n".format(x.shape))
            
        return x
    
model = TestModel()
x = tf.random.normal(shape = (32, 28, 28, 3))
predictions =  model(x)

print("Input: {}".format(x.shape))
print("Output: {}".format(predictions.shape))

for layer in model.layers:
    W, B = layer.get_weights()
    print("Weights: {}, Biases: {}".format(W.shape, B.shape))
    
print("=========================")
trainable_variables = model.trainable_variables
for train_var in trainable_variables:
    print("Shape: {}".format(train_var.shape))
    

Input  (32, 28, 28, 3)

===== Conv Layers =====

W/B: (3, 3, 3, 10)/(10,)
X: (32, 26, 26, 10)

W/B: (3, 3, 10, 20)/(20,)
X: (32, 24, 24, 20)

W/B: (3, 3, 20, 30)/(30,)
X: (32, 22, 22, 30)

Input: (32, 28, 28, 3)
Output: (32, 22, 22, 30)
Weights: (3, 3, 3, 10), Biases: (10,)
Weights: (3, 3, 10, 20), Biases: (20,)
Weights: (3, 3, 20, 30), Biases: (30,)
Shape: (3, 3, 3, 10)
Shape: (10,)
Shape: (3, 3, 10, 20)
Shape: (20,)
Shape: (3, 3, 20, 30)
Shape: (30,)


In [6]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.models import Model

n_neurons = [10, 20, 30]

class TestModel(Model):
    def __init__(self):
        super(TestModel, self).__init__()
        global n_neurons
        
        self.conv1 = Conv2D(filters = n_neurons[0], kernel_size = 3, activation = 'relu')
        self.conv2 = Conv2D(filters = n_neurons[1], kernel_size = 3, activation = 'relu')
        self.conv3 = Conv2D(filters = n_neurons[2], kernel_size = 3, activation = 'relu')
        
        
    def __call__(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        
        return x