# 6-1: Max/Avg Pooling

### Code.6-1-1: Max Pooling

In [5]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling1D

Length, pooling_size, stride = 10, 2, 1

                        # 데이터 갯수       열
x = tf.random.normal(shape = (1, Length, 1))
                                # 길이(행)
                          
pool_max = MaxPooling1D(pool_size = pooling_size, strides = stride)
pooled_max = pool_max(x)

print("x:{}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max.numpy().flatten()))

x = x.numpy().flatten()
pooled_max_man = np.zeros((Length - pooling_size + 1, ))

for i in range(Length - pooling_size + 1):
    window = x[i:i+pooling_size]
    pooled_max_man[i] = np.max(window)
    
print("pooled_max(Manual): {}\n{}".format(pooled_max.shape,
                                          pooled_max_man))

x:(1, 10, 1)
[-1.3544159   0.7045493   0.03666191  0.86918795  0.43842277 -0.53439844
 -0.07710292  1.5658046  -0.1012345  -0.2744975 ]
pooled_max(Tensorflow): (1, 9, 1)
[ 0.7045493   0.7045493   0.86918795  0.86918795  0.43842277 -0.07710292
  1.5658046   1.5658046  -0.1012345 ]
pooled_max(Manual): (1, 9, 1)
[ 0.70454931  0.70454931  0.86918795  0.86918795  0.43842277 -0.07710292
  1.5658046   1.5658046  -0.1012345 ]


### Code.6-1-2: Average Pooling

In [9]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import AveragePooling1D

Length, pool_size, stride = 10, 2, 1
                        # 데이터 갯수     # (열)
x = tf.random.normal(shape = (1, Length, 1))
                                # 길이 (행)
  
pool_avg = AveragePooling1D(pool_size = pooling_size, strides = stride)
pooled_avg = pool_avg(x)

print("x:{}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape,
                                              pooled_avg.numpy().flatten()))

x = x.numpy().flatten()
pooled_avg_man = np.zeros((Length - pooling_size + 1, ))

for i in range(Length - pooling_size + 1):
    window = x[i:i+pooling_size]
    pooled_avg_man[i] = np.mean(window)

print("pooled_avg(Manual): {}\n{}".format(pooled_avg_man.shape,
                                          pooled_avg_man))

x:(1, 10, 1)
[-1.3544159   0.7045493   0.03666191  0.86918795  0.43842277 -0.53439844
 -0.07710292  1.5658046  -0.1012345  -0.2744975 ]
pooled_avg(Tensorflow): (1, 9, 1)
[-0.3249333   0.37060562  0.45292494  0.6538054  -0.04798783 -0.30575067
  0.74435085  0.732285   -0.187866  ]
pooled_avg(Manual): (9,)
[-0.32493329  0.37060562  0.45292494  0.65380538 -0.04798783 -0.30575067
  0.74435085  0.73228502 -0.187866  ]


# 6-2: 2D Max/Avg Pooling

### Code.6-2-1: 2D Max Pooling

In [11]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1

pooling_size, stride = 2, 1

x = tf.random.normal(shape = (N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size = pooling_size, strides = stride)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape = (n_H - pooling_size + 1, n_W - pooling_size + 1))

for i in range(n_H - pooling_size + 1):
    for j in range(n_W - pooling_size + 1):
        window = x[i:i+pooling_size, j:j+pooling_size]
        pooled_max_man[i, j] = np.max(window)
print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape,
                                          pooled_max_man))



x: (1, 5, 5, 1)
[[-1.3544159   0.7045493   0.03666191  0.86918795  0.43842277]
 [-0.53439844 -0.07710292  1.5658046  -0.1012345  -0.2744975 ]
 [ 1.420466    1.2609465  -0.4364091  -1.963399   -0.06452482]
 [-1.056841    1.0019135   0.6735137   0.06987705 -1.4077919 ]
 [ 1.0278524   0.2797411  -0.01347954  1.8451811   0.9706112 ]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[ 0.7045493   1.5658046   1.5658046   0.86918795]
 [ 1.420466    1.5658046   1.5658046  -0.06452482]
 [ 1.420466    1.2609465   0.6735137   0.06987705]
 [ 1.0278524   1.0019135   1.8451811   1.8451811 ]]
pooled_max(Manual): (4, 4)
[[ 0.70454931  1.5658046   1.5658046   0.86918795]
 [ 1.42046595  1.5658046   1.5658046  -0.06452482]
 [ 1.42046595  1.26094651  0.67351371  0.06987705]
 [ 1.02785242  1.00191355  1.84518111  1.84518111]]


### Code.6-2-2: 2D Average Pooling

In [13]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1

pooling_size, stride = 2, 1

x = tf.random.normal(shape = (N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size = pooling_size, strides = stride)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_avg.shape,
                                              pooled_avg.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape = (n_H - pooling_size + 1, n_W - pooling_size + 1))

for i in range(n_H - pooling_size + 1):
    for j in range(n_W - pooling_size + 1):
        window = x[i:i+pooling_size, j:j+pooling_size]
        pooled_avg_man[i,j] = np.mean(window)
        
print("pooled_max(Manual): {}\n{}".format(pooled_avg_man.shape,
                                          pooled_avg_man))

    


x: (1, 5, 5, 1)
[[-1.3544159   0.7045493   0.03666191  0.86918795  0.43842277]
 [-0.53439844 -0.07710292  1.5658046  -0.1012345  -0.2744975 ]
 [ 1.420466    1.2609465  -0.4364091  -1.963399   -0.06452482]
 [-1.056841    1.0019135   0.6735137   0.06987705 -1.4077919 ]
 [ 1.0278524   0.2797411  -0.01347954  1.8451811   0.9706112 ]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[-0.31534198  0.55747825  0.592605    0.2329697 ]
 [ 0.51747775  0.5783098  -0.23380953 -0.600914  ]
 [ 0.6566212   0.6249912  -0.41410437 -0.84145963]
 [ 0.3131665   0.48542216  0.6437731   0.36946937]]
pooled_max(Manual): (4, 4)
[[-0.31534198  0.55747825  0.59260499  0.2329697 ]
 [ 0.51747775  0.57830977 -0.23380953 -0.600914  ]
 [ 0.65662122  0.62499118 -0.41410437 -0.84145963]
 [ 0.3131665   0.48542216  0.64377308  0.36946937]]


# 6-3: 3D Max/Avg Pooling

### Code.6-3-1: 3D Max Pooling

In [16]:
import math
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 3
pooling_size, stride = 2, 2

x = tf.random.normal(shape = (N, n_H, n_W, n_C))
print("x: {}\n{}".format(x.shape, np.transpose(x.numpy().squeeze()), (2, 0, 1)))

pool_max = MaxPooling2D(pool_size = pooling_size, strides = stride)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(), (2, 0, 1))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max_t))

# [[[0.86918795 0.9706112 ]         R
#   [0.842157   0.60545963]]

#  [[1.0019135  1.5658046 ]         G
#   [0.28291693 0.37944326]]

#  [[1.0278524  1.8451811 ]         B
#   [1.2132235  0.80458266]]]


x = x.numpy().squeeze()
n_H_ = math.floor((n_H - pooling_size) / stride + 1) # floor 함수는 실수를 입력하면내림하여 정수를 반환하는 함수
n_W_ = math.floor((n_W - pooling_size) / stride + 1)
pooled_max_man = np.zeros(shape = (n_H_, n_W_, n_C))

for c in range(n_C):
    c_image = x[:, :, c]
    h_ = 0     # start      stop               steps
    for h in range(0, n_H - pooling_size + 1, stride):
        w_ = 0
        for w in range(0, n_W - pooling_size + 1, stride):
            window = c_image[h:h+pooling_size, w:w_+pooling_size]
            pooled_max_man[h_, w_, c] = np.max(window)
            
            w_ += 1
        h_ += 1

pooled_max_t = np.transpose(pooled_max_man, (2, 0, 1))
print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape,
                                          pooled_max_t))


            


x: (1, 5, 5, 3)
[[[-1.3544159  -1.056841   -0.87579006 -0.29925638  0.3314997 ]
  [ 0.86918795  0.06987705  0.842157   -1.0130817   0.593032  ]
  [-0.07710292  0.2797411  -0.6039788   0.46988976 -1.0939722 ]
  [-0.2744975   0.9706112   0.29037958  0.60545963 -0.16822565]
  [-0.4364091  -0.29738778  0.01063002  0.47690514  0.35877225]]

 [[ 0.7045493   1.0019135  -0.08856997 -0.36523244 -0.5445253 ]
  [ 0.43842277 -1.4077919  -0.06378508  0.28291693 -0.63509274]
  [ 1.5658046  -0.01347954 -0.17669262  0.37944326 -0.46014464]
  [ 1.420466   -1.0242516  -0.2960446   0.19181171 -0.43908644]
  [-1.963399   -1.3240397   1.5165399  -0.7812124  -1.9095895 ]]

 [[ 0.03666191  0.6735137   0.6921164   0.61883324  1.5222509 ]
  [-0.53439844  1.0278524   0.9280078   1.2132235   0.3703566 ]
  [-0.1012345   1.8451811   0.04221032 -0.66640246  1.5420506 ]
  [ 1.2609465  -0.6544423  -0.21134192  0.80458266 -0.41292417]
  [-0.06452482  0.28785658  0.27305746 -0.996891   -0.20947677]]]
pooled_max(Tensorf

# 6-4: Padding

### Code.6-4-1: Zero Padding 2D Layer

In [21]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape = (1, 3, 3, 3))
print(images.shape)
print(np.transpose(images.numpy().squeeze(), (2, 0, 1)))

# [[[-1.3544159   0.86918795 -0.07710292]       R
#   [-0.2744975  -0.4364091  -1.056841  ]
#   [ 0.06987705  0.2797411   0.9706112 ]]

#  [[ 0.7045493   0.43842277  1.5658046 ]       G
#   [ 1.420466   -1.963399    1.0019135 ]
#   [-1.4077919  -0.01347954 -1.0242516 ]]

#  [[ 0.03666191 -0.53439844 -0.1012345 ]       B
#   [ 1.2609465  -0.06452482  0.6735137 ]
#   [ 1.0278524   1.8451811  -0.6544423 ]]]


zero_padding = ZeroPadding2D(padding = 1)
y = zero_padding(images)
print(y.shape)
print(np.transpose(y.numpy().squeeze(), (2, 0 ,1)))

# [[[ 0.          0.          0.          0.          0.        ]       
#   [ 0.         -1.3544159   0.86918795 -0.07710292  0.        ]       R
#   [ 0.         -0.2744975  -0.4364091  -1.056841    0.        ]
#   [ 0.          0.06987705  0.2797411   0.9706112   0.        ]
#   [ 0.          0.          0.          0.          0.        ]]

#  [[ 0.          0.          0.          0.          0.        ]
#   [ 0.          0.7045493   0.43842277  1.5658046   0.        ]       G
#   [ 0.          1.420466   -1.963399    1.0019135   0.        ]
#   [ 0.         -1.4077919  -0.01347954 -1.0242516   0.        ]
#   [ 0.          0.          0.          0.          0.        ]]

#  [[ 0.          0.          0.          0.          0.        ]
#   [ 0.          0.03666191 -0.53439844 -0.1012345   0.        ]       B
#   [ 0.          1.2609465  -0.06452482  0.6735137   0.        ]
#   [ 0.          1.0278524   1.8451811  -0.6544423   0.        ]
#   [ 0.          0.          0.          0.          0.        ]]]



(1, 3, 3, 3)
[[[-1.3544159   0.86918795 -0.07710292]
  [-0.2744975  -0.4364091  -1.056841  ]
  [ 0.06987705  0.2797411   0.9706112 ]]

 [[ 0.7045493   0.43842277  1.5658046 ]
  [ 1.420466   -1.963399    1.0019135 ]
  [-1.4077919  -0.01347954 -1.0242516 ]]

 [[ 0.03666191 -0.53439844 -0.1012345 ]
  [ 1.2609465  -0.06452482  0.6735137 ]
  [ 1.0278524   1.8451811  -0.6544423 ]]]
(1, 5, 5, 3)
[[[ 0.          0.          0.          0.          0.        ]
  [ 0.         -1.3544159   0.86918795 -0.07710292  0.        ]
  [ 0.         -0.2744975  -0.4364091  -1.056841    0.        ]
  [ 0.          0.06987705  0.2797411   0.9706112   0.        ]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.          0.        ]
  [ 0.          0.7045493   0.43842277  1.5658046   0.        ]
  [ 0.          1.420466   -1.963399    1.0019135   0.        ]
  [ 0.         -1.4077919  -0.01347954 -1.0242516   0.        ]
  [ 0.          0.          0.

### Code.6-4-2: Zero Padding with Conv2D Layers

In [22]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape = (1, 28, 28, 3))

# conv layer 에서는 same 또는 valid padding을 주로 사용
# same padding 은 윈도우가 움직일 때 코너 케이스를 계산해줘 사이즈가 줄어들지 않도록 패딩을 자동으로 해준다.
# (1, 28, 28, 3) -> (1, 30, 30, 3)
conv = Conv2D(filters = 1, kernel_size = 3, padding = 'same') 
y = conv(images)
print(y.shape) # (1, 28, 28, 1)

(1, 28, 28, 1)


# 6-5: Strides

### Code.6-5-1: Strides in Conv2D Layers

In [23]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape = (1, 28, 28, 3))
conv = Conv2D(filters = 1, kernel_size = 3, padding = 'valid', strides = 2)
y = conv(images)

print(images.shape)
print(y.shape)


(1, 28, 28, 3)
(1, 13, 13, 1)


### Code.6-5-2: Strides in Pooling Layers

In [26]:
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape = (1, 28, 28, 3))
conv = MaxPooling2D(pool_size = 3, strides = 2, padding = 'valid')
y = conv(images)

print(images.shape)
print(y.shape) 


(1, 28, 28, 3)
(1, 13, 13, 3)
