# 7-1: Shapes in CNN

### Code.7-1-1: Shapes in the Feature Extractors

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten

N, n_H, n_W, n_C = 32, 28, 28, 3
n_conv_filters = 5
k_size = 3
pool_size, pool_strides = 2, 2
batch_size = 32

x = tf.random.normal(shape = (N, n_H, n_W, n_C))

conv1 = Conv2D(filters = n_conv_filters, kernel_size = k_size,
               padding = 'same', activation = 'relu')
conv1_pool = MaxPooling2D(pool_size = pool_size, strides = pool_strides)



conv2 = Conv2D(filters = n_conv_filters, kernel_size = k_size,
               padding = 'same', activation = 'relu')
conv2_pool = MaxPooling2D(pool_size = pool_size, strides = pool_strides)

flatten = Flatten()

print("Input: {}".format(x.shape))
# Input: (32, 28, 28, 3)

x = conv1(x)
print("After conv1: {}".format(x.shape))
# After conv1: (32, 28, 28, 5) : same padding 으로 설정했기 떄문에 W, H값이 바뀌지 않지만 
#                               filter 갯수가 5개 였기 떄문에 5채널로 바뀜
x = conv1_pool(x)
print("After conv1_pool:{}".format(x.shape))
# After conv1_pool:(32, 14, 14, 5)

x = conv2(x)
print("After conv2: {}".format(x.shape))

W, B = conv2.get_weights()
print("W/B: {}/{}".format(W.shape, B.shape))

x = conv2_pool(x)
print("After conv2_pool: {}".format(x.shape))

x = flatten(x)
print("After flatten:{}".format(x.shape))

Input: (32, 28, 28, 3)
After conv1: (32, 28, 28, 5)
After conv1_pool:(32, 14, 14, 5)
After conv2: (32, 14, 14, 5)
W/B: (3, 3, 5, 5)/(5,)
After conv2_pool: (32, 7, 7, 5)
After flatten:(32, 245)


### Code.7-1-2: Shapes in the Calssifier

In [10]:
import tensorflow as tf
from tensorflow.keras.layers import Dense 


n_neurons = [50, 25, 10]
dense1 = Dense(units = n_neurons[0], activation = 'relu')
dense2 = Dense(units = n_neurons[1], activation = 'relu')
dense3 = Dense(units = n_neurons[2], activation = 'softmax')


print("Input feature: {}".format(x.shape))
x = dense1(x)
W, B = dense1.get_weights()
print("W/B: {}/{}".format(W.shape, B.shape))
print("After dense1: {}".format(x.shape))

x = dense2(x)
W, B = dense2.get_weights()
print("W/B: {}/{}".format(W.shape, B.shape))
print("After dense2: {}".format(x.shape))

x = dense3(x)
W, B = dense3.get_weights()
print("W/B :{}/{}".format(W.shape, B.shape))
print("After dense3: {}".format(x.shape))


Input feature: (32, 245)
W/B: (245, 50)/(50,)
After dense1: (32, 50)
W/B: (50, 25)/(25,)
After dense2: (32, 25)
W/B :(25, 10)/(10,)
After dense3: (32, 10)


### Code.7-1-3: Shapes in the Loss Functions

In [11]:
import tensorflow as tf
from tensorflow.keras.losses import CategoricalCrossentropy


y = tf.random.uniform(minval = 0, maxval = 10,
                      shape = (32, ),
                      dtype = tf.int32)

y = tf.one_hot(y, depth = 10)
print(y)

loss_object = CategoricalCrossentropy()
loss = loss_object(y, x)
print(loss.shape)
print(loss)

tf.Tensor(
[[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]

# 7-1: Implementation of CNNs

### Code.7-1-1: Implementation with Sequential Method

In [5]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense 

N, n_H, n_W, n_C = 4, 28, 28, 3
n_conv_neurons = [10, 20, 30]
n_dense_neurons = [50, 30, 10]
k_size, padding = 3, 'same'
activation = 'relu'
pool_size, pool_strides = 2, 2

x = tf.random.normal(shape = (N, n_H, n_W, n_C))
print(x.shape)

model = Sequential()
model.add(Conv2D(filters = n_conv_neurons[0], kernel_size = k_size, padding = padding,
                 activation = activation))
model.add(MaxPooling2D(pool_size = pool_size, strides = pool_strides))

model.add(Conv2D(filters = n_conv_neurons[1], kernel_size = k_size, padding = padding,
                 activation = activation))
model.add(MaxPooling2D(pool_size = pool_size, strides = pool_strides))

model.add(Conv2D(filters = n_conv_neurons[2], kernel_size = k_size, padding = padding,
                 activation = activation))
model.add(MaxPooling2D(pool_size = pool_size, strides = pool_strides))

model.add(Flatten())

model.add(Dense(units = n_dense_neurons[0], activation = activation))
model.add(Dense(units = n_dense_neurons[1], activation = activation))
model.add(Dense(units = n_dense_neurons[2], activation = 'softmax'))

predictions = model(x)
print(predictions.shape)




(4, 28, 28, 3)
(4, 10)


In [ ]:
model = Sequential()

for n_conv_neurons in n_conv_neurons:
    model.add(Conv2D(filters = n_conv_neurons, kernel_size = k_size, padding = padding,
                     activation = activation))
    model.add(MaxPooling2D(pool_size = pool_size, strides = pool_strides))
model.add(Flatten())

for n_dense_neuron in n_dense_neurons:
    model.add(Dense(units = n_dense_neurons, activation = activation))
model.add(Dense(units = n_dense_neuron[-1], activation = 'softmax'))

### Code.7-1-2: Implementation with Model Sub-classing

In [10]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D
from tensorflow.keras.layers import MaxPooling2D
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Dense 


class TestCNN(Model):
    def __init__(self):
        super(TestCNN, self).__init__()
        
        self.conv1 = Conv2D(filters = n_conv_neurons[0], kernel_size = k_size, padding = padding,
                            activation = activation)
        self.conv1_pool = MaxPooling2D(pool_size = pool_size, strides = pool_strides)
        
        self.conv2 = Conv2D(filters = n_conv_neurons[1], kernel_size = k_size, padding = padding,
                            activation = activation)
        self.conv2_pool = MaxPooling2D(pool_size = pool_size, strides = pool_strides)
        
        self.conv3 = Conv2D(filters = n_conv_neurons[2], kernel_size = k_size, padding = padding,
                            activation = activation)
        self.conv3_pool = MaxPooling2D(pool_size = pool_size, strides = pool_strides)
        self.flatten = Flatten()
        
        self.dense1 = Dense(units = n_dense_neurons[0], activation = activation)
        self.dense2 = Dense(units = n_dense_neurons[1], activation = activation)
        self.dense3 = Dense(units = n_dense_neurons[2], activation = 'softmax')
        
    def __call__(self, x):
        print(x.shape)
        x = self.conv1(x)
        print(x.shape)
        x = self.conv1_pool(x)
        print(x.shape)
        
        x = self.conv2(x)
        print(x.shape)
        x = self.conv2_pool(x)
        print(x.shape)
        
        x = self.conv3(x)
        print(x.shape)
        x = self.conv3_pool(x)
        print(x.shape)
        
        x = self.flatten(x)
        print(x.shape)
        
        x = self.dense1(x)
        print(x.shape)
        x = self.dense2(x)
        print(x.shape)
        x = self.dense3(x)
        
        return x
    
    
N, n_H, n_W, n_C = 4, 28, 28, 3
n_conv_neurons = [10, 20, 30]
n_dense_neurons = [50, 30, 10]
k_size, padding = 3, 'same'
activation = 'relu'
pool_size, pool_strides = 2, 2

x = tf.random.normal(shape = (N, n_H, n_W, n_C))

model = TestCNN()
y = model(x)
print(y.shape)
        
        
        
        

(4, 28, 28, 3)
(4, 28, 28, 10)
(4, 14, 14, 10)
(4, 14, 14, 20)
(4, 7, 7, 20)
(4, 7, 7, 30)
(4, 3, 3, 30)
(4, 270)
(4, 50)
(4, 30)
(4, 10)


### Code.7-1-3: Implementation with Sequential + Layer Sub-classing

In [1]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Layer, Conv2D, MaxPooling2D, Flatten, Dense 

class MyConv(Layer):
    def __init__(self, n_neurons):
        super(MyConv, self).__init__()
        
        self.conv = Conv2D(filters = n_neurons, kernel_size = k_size, padding = padding,
                           activation = activation)
        
        self.conv_pool = MaxPooling2D(pool_size = pool_size, strides = pool_strides)
        
    def __call__(self, x):
        x = self.conv(x)
        x = self.conv_pool(x)
        return x
    
N, n_H, n_W, n_C = 4, 28, 28, 3
n_conv_neurons = [10, 20, 30]
n_dense_neurons = [50, 30, 10]
k_size, padding = 3, 'same'
activation = 'relu'
pool_size, pool_strides = 2, 2

x = tf.random.normal(shape = (N, n_H, n_W, n_C))

model = Sequential()
model.add(MyConv(n_conv_neurons[0]))
model.add(MyConv(n_conv_neurons[1]))
model.add(MyConv(n_conv_neurons[2]))
model.add(Flatten())

model.add(Dense(units = n_dense_neurons[0], activation = activation))
model.add(Dense(units = n_dense_neurons[1], activation = activation))
model.add(Dense(units = n_dense_neurons[2], activation = 'softmax'))

y = model(x)
print(y.shape)

Metal device set to: Apple M1 Pro

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

(4, 10)


### Code.7-1-4: Implementation with Model and Layer Sub-classing

In [3]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Layer, Conv2D, MaxPooling2D, Flatten, Dense


class MyConv(Layer):
    def __init__(self, n_neurons):
        super(MyConv, self).__init__()
        
        self.conv = Conv2D(filters = n_neurons, kernel_size = k_size, padding = padding,
                           activation = activation)
        self.conv_pool = MaxPooling2D(pool_size = pool_size, strides = pool_strides)
        
        
    def __call__(self, x):
        x = self.conv(x)
        x = self.conv_pool(x)
        return x
    
    
class TestCNN(Model):
    def __init__(self):
        super(TestCNN, self).__init__()
    
        self.conv1 = MyConv(n_conv_neurons[0])
        self.conv2 = MyConv(n_conv_neurons[1])
        self.conv3 = MyConv(n_conv_neurons[2])
        self.flatten = Flatten()
        
        self.dense1 = Dense(units = n_dense_neurons[0], activation = activation)
        self.dense2 = Dense(units = n_dense_neurons[1], activation = activation)
        self.dense3 = Dense(units = n_dense_neurons[2], activation = 'softmax')
        
    def __call__(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.flatten(x)
        
        x = self.dense1(x)
        x = self.dense2(x)
        x = self.dense3(x)
        
        return x
    
N, n_H, n_W, n_C = 4, 28, 28, 3
n_conv_neurons = [10, 20, 30]
n_dense_neurons = [50, 30, 10]
k_size, padding = 3, 'same'
activation = 'relu'
pool_size, pool_strides = 2, 2

x = tf.random.normal(shape = (N, n_H, n_W, n_C))

model = TestCNN()
y = model(x)

print(y.shape)



        
        
        

(4, 10)


In [4]:
import tensorflow as tf
from tensorflow.keras.models import Sequential, Model
from tensorflow.keras.layers import Layer, Conv2D, MaxPooling2D, Flatten, Dense

class MyConv(Layer):
    def __init__(self, n_neuron):
        super(MyConv, self).__init__()
        
        self.conv = Conv2D(filters = n_neuron, kernel_size = k_size, padding = padding,
                           activation = activation)
        
        self.conv_pool = MaxPooling2D(pool_size = pool_size, strides = pool_strides)
        
    def __call__(self, x):
        x = self.conv(x)
        x = self.conv_pool(x)
        return x
    

class TestCNN(Model):
    def __init__(self):
        super(TestCNN, self).__init__()
        
        self.feature_extractor = Sequential()
        self.feature_extractor.add(MyConv(n_conv_neurons[0]))
        self.feature_extractor.add(MyConv(n_conv_neurons[1]))
        self.feature_extractor.add(MyConv(n_conv_neurons[2]))
        self.feature_extractor.add(Flatten())
        
        self.classifier = Sequential()
        self.classifier.add(Dense(units = n_dense_neurons[0], activation = activation))
        self.classifier.add(Dense(units = n_dense_neurons[1], activation = activation))
        self.classifier.add(Dense(units = n_dense_neurons[2], activation = 'softmax'))
        
        
    def __call__(self, x):
        x = self.feature_extractor(x)
        x = self.classifier(x)
        return x
    
model = TestCNN()
y = model(x)
print(y.shape)

(4, 10)


# 7-2: Implementation of LeNet

### Code.7-2-1: LeNet with Model Sub-classing

In [13]:
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Conv2D, AveragePooling2D, Flatten, Dense

class LeNet(Model):
    def __init__(self):
        super(LeNet, self).__init__()
        
        self.conv1 = Conv2D(filters = 6, kernel_size = 5, padding = 'same',
                            activation = 'tanh')
        self.conv1_pool = AveragePooling2D(pool_size = 2, strides = 2)
        
        self.conv2 = Conv2D(filters = 16, kernel_size = 5, padding = 'valid',
                            activation = 'tanh')
        self.conv2_pool = AveragePooling2D(pool_size = 2, strides = 2)
        
        self.conv3 = Conv2D(filters = 120, kernel_size = 5, padding = 'valid',
                            activation = 'tanh')
        
        self.flatten = Flatten()
        
        self.dense1 = Dense(units = 84, activation = 'tanh')
        self.dense2 = Dense(units = 10, activation = 'softmax')
        
    def __call__(self, x):
        print('x: \n{}'.format(x.shape))
        
        x = self.conv1(x)
        print('\nconv1 x \n{}'.format(x.shape))
        
        x = self.conv1_pool(x)
        print('\nconv1_pool x \n{}'.format(x.shape))
        
        x = self.conv2(x)
        print('\nconv2 x \n{}'.format(x.shape))
        
        x = self.conv2_pool(x)
        print('\nconv2_pool x \n{}'.format(x.shape))
        
        x = self.conv3(x)
        print('\nconv3 x \n{}'.format(x.shape))
        
        x = self.flatten(x)
        print('\nflatten x \n{}'.format(x.shape))
        
        x = self.dense1(x)
        print('\ndense1 x \n{}'.format(x.shape))
        
        x = self.dense2(x)
        print('\ndense2 x \n{}'.format(x.shape))
        
        return x
    
model = LeNet()
x = tf.random.normal(shape = (32, 28, 28, 1))
predictions = model(x)
print('\npredictions:',predictions.shape)

x: 
(32, 28, 28, 1)

conv1 x 
(32, 28, 28, 6)

conv1_pool x 
(32, 14, 14, 6)

conv2 x 
(32, 10, 10, 16)

conv2_pool x 
(32, 5, 5, 16)

conv3 x 
(32, 1, 1, 120)

flatten x 
(32, 120)

dense1 x 
(32, 84)

dense2 x 
(32, 10)

predictions: (32, 10)


### Code.7-2-2: LeNet with Hybrid Method

In [33]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer, Conv2D, AveragePooling2D, Flatten, Dense

from tensorflow.keras.datasets import mnist
from tensorflow.keras.losses import SparseCategoricalCrossentropy


class ConvLayer(Layer):
    def __init__(self, filters, padding, pool = True):
        super(ConvLayer, self).__init__()
        self.pool = pool
        self.filters = filters
        self.padding = padding 
        
        self.conv = Conv2D(filters = self.filters, kernel_size = 5, padding = self.padding,
                           activation = 'tanh')
        if self.pool == True:
            self.conv_pool = AveragePooling2D(pool_size = 2, strides = 2)
            
    def __call__(self, x):
        x = self.conv(x)
        
        if self.pool == True:
            x = self.conv_pool(x)
        
        return x
    

class LeNet(Model):
    def __init__(self):
        super(LeNet, self).__init__()
        
        self.conv1 = ConvLayer(filters = 6, padding = 'same')
        self.conv2 = ConvLayer(filters = 16, padding = 'valid')
        self.conv3 = ConvLayer(filters = 120, padding = 'valid', pool = False)
        self.flatten = Flatten()
        
        self.dense1 = Dense(units = 84, activation = 'tanh')
        self.dense2 = Dense(units = 10, activation = 'softmax')
        
    def __call__(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        x = self.flatten(x)
        
        x = self.dense1(x)
        x = self.dense2(x)
        
        return x
    
(train_images, train_labels), _ = mnist.load_data()
print(train_images.shape, train_images.dtype)
print(train_labels.shape, train_labels.dtype)

train_images = np.expand_dims(train_images, axis = 3).astype(np.float32)
print(train_images.shape, train_images.dtype)

train_labels = train_labels.astype(np.int32)


train_dataset = tf.data.Dataset.from_tensor_slices((train_images, train_labels))
train_dataset = train_dataset.batch(32)

model = LeNet()
loss_object = SparseCategoricalCrossentropy()

for images, labels in train_dataset:
    predictions = model(images)
    loss = loss_object(labels, predictions)
    print(loss)
    break



        
        

(60000, 28, 28) uint8
(60000,) uint8
(60000, 28, 28, 1) float32
tf.Tensor(2.349094, shape=(), dtype=float32)


# Practice

In [13]:
import numpy as np
import tensorflow as tf 
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Layer, Conv2D, AveragePooling2D, Flatten, Dense
from tensorflow.keras.losses import SparseCategoricalCrossentropy
from tensorflow.keras.datasets import mnist

# LeNet        Filter Size      Filters     Padding     Strides     Activation      Output
# input                            1                                                28 | 28 | 1

# Conv1             5              6           2           1           tanh         28 | 28 | 6
# AvgPool1          2              -           0           2                        14 | 14 | 6
# Conv2             5             16           0           1           tanh         10 | 10 | 16
# AvgPool2          2              -           0           2                         5 |  5 | 16
# Conv3             5             120          0           1           tanh          1 |  1 | 120

# Flatten                                                                          120 |
# Dense1                          84                                   tanh         84 |
# Dense2                          10                                   softmax      10 |

class ConvLayer(Layer):
    def __init__(self, filters, padding, pool = True):
        super(ConvLayer, self).__init__()
        
        self.filters = filters
        self.padding = padding
        self.pool = pool
        
        self.conv = Conv2D(filters = self.filters, kernel_size = 5, padding = self.padding, 
                           activation = 'tanh')
        
        if self.pool == True:
            self.conv_pool = AveragePooling2D(pool_size = 2, padding = 'valid', strides = 2)
            
    def __call__(self, x):
        x = self.conv(x)
        
        if self.pool == True:
            x = self.conv_pool(x)
        
        return x
            

class LeNet(Model):
    def __init__(self):
        super(LeNet, self).__init__()
        
        self.conv1 = ConvLayer(filters = 6, padding = 'same')
        self.conv2 = ConvLayer(filters = 16, padding = 'valid')
        self.conv3 = ConvLayer(filters = 120, padding = 'valid', pool = False)
        
        self.flatten = Flatten()
        self.dense1 = Dense(units = 84, activation = 'tanh')
        self.dense2 = Dense(units = 10, activation = 'softmax')
        
    def __call__(self, x):
        x = self.conv1(x)
        x = self.conv2(x)
        x = self.conv3(x)
        
        x = self.flatten(x)
        x = self.dense1(x)
        x = self.dense2(x)
        
        return x
    
(test_images, test_labels), _ = mnist.load_data()
# print(test_images.shape)

test_images = np.expand_dims(test_images, axis = 3).astype(np.float32)
test_labels = test_labels.astype(np.int32)

dataset = tf.data.Dataset.from_tensor_slices((test_images, test_labels))
dataset = dataset.batch(32)

model = LeNet()
loss_object = SparseCategoricalCrossentropy()
for image, label in dataset:
    print(image.shape)
    predict = model(image)
    loss = loss_object(label, predict)
    
    print(loss)
    break

(32, 28, 28, 1)
tf.Tensor(2.301944, shape=(), dtype=float32)
