# 1-1: Affine Functions with 1 Feature

### Code. 1-1-1: Affine Function

In [3]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.constant([[10.]]) # input setting(Note: input -> matrix)
print(x.shape)
print(x)
dense = Dense(units=1, activation='linear') # imp. an affine function

y_tf = dense(x) # forward propagation + params initialization (z = x * w + b)
print(y_tf)

W, B = dense.get_weights() # get weight, bias
print(W, B)

y_man = tf.linalg.matmul(x, W) + B # forward promagation(manual)
# matmul : matrix multiplication

# print result
print('====== Input/Weight/Bias ======')
print('x_shape: {}\n{}\n'.format(x.shape, x.numpy()))
print('W_shape: {}\nP{}\n'.format(W.shape, W))
print('B_shape: {}\nP{}\n'.format(B.shape, B))


print('====== Outputs ======')
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))




Metal device set to: Apple M1 Pro
(1, 1)

systemMemory: 32.00 GB
maxCacheSize: 10.67 GB

tf.Tensor([[10.]], shape=(1, 1), dtype=float32)
tf.Tensor([[12.438742]], shape=(1, 1), dtype=float32)
[[1.2438742]] [0.]
====== Input/Weight/Bias ======
x_shape: (1, 1)
[[10.]]

W_shape: (1, 1)
P[[1.2438742]]

B_shape: (1,)
P[0.]

====== Outputs ======
y(Tensorflow): (1, 1)
[[12.438742]]

y(Manual): (1, 1)
[[12.438742]]



### Code.1-1-1 : Params Initialization

In [20]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant 

# weight/bias setting
w, b = tf.constant(10.), tf.constant(20.) # 실제 텐서 값이 아님
w_init, b_init = tf.keras.initializers.Constant(w), Constant(b) # w, b 초기화 오브젝트

print(w_init, b_init)

# imp. an affine function
dense = Dense(units = 1, 
              activation='linear',
              kernel_initializer=w_init,
              bias_initializer=b_init)

x = tf.constant([[10.]]) # z = x * w + b (10 * 10 + 20)
y_tf = dense(x)
print(y_tf) # 120

W, B = dense.get_weights()
# print result 
print("W: {}\n{}".format(W.shape, W))
print("B: {}\n{}\n".format(B.shape, B))


<keras.initializers.initializers_v2.Constant object at 0x107895c60> <keras.initializers.initializers_v2.Constant object at 0x107894250>
tf.Tensor([[120.]], shape=(1, 1), dtype=float32)
W: (1, 1)
[[10.]]
B: (1,)
[20.]



# 1-2: Affine Functions with N Features

### Code.1-2-1 : Affine Functions with N Features

In [26]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.initializers import Constant

x = tf.random.uniform(shape=(1,10), minval=0, maxval=10)
# print(x, '\n' ,x.shape)

dense = Dense(units = 1)

y_tf = dense(x)

W,B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B

# print result
print('====== Input/Weight/Bias ======')
print('x_shape: {}\n{}\n'.format(x.shape, x.numpy()))
print('W_shape: {}\nP{}\n'.format(W.shape, W))
print('B_shape: {}\nP{}\n'.format(B.shape, B))


print('====== Outputs ======')
print("y(Tensorflow): {}\n{}\n".format(y_tf.shape, y_tf.numpy()))
print("y(Manual): {}\n{}\n".format(y_man.shape, y_man.numpy()))

====== Input/Weight/Bias ======
x_shape: (1, 10)
[[3.1179297  8.263412   6.849456   0.06709099 7.8749514  3.906511
  2.9263055  9.921693   9.581042   5.5623317 ]]

W_shape: (10, 1)
P[[ 0.68710214]
 [-0.1210326 ]
 [-0.5607531 ]
 [-0.72845984]
 [ 0.30647546]
 [ 0.21355563]
 [ 0.66414386]
 [-0.31598148]
 [ 0.2962156 ]
 [ 0.10126787]]

B_shape: (1,)
P[0.]

====== Outputs ======
y(Tensorflow): (1, 1)
[[2.7099597]]

y(Manual): (1, 1)
[[2.7099597]]

