# 1-3 : Activation Functions

### Code. 1-3-1: Activation Layers

In [23]:
import tensorflow as tf
from tensorflow.math import exp, maximum
from tensorflow.keras.layers import Activation

x = tf.random.normal(shape=(1,5)) # input setting

#imp. activation function
sigmoid = Activation('sigmoid')
tanh = Activation('tanh')
relu = Activation('relu')

# forward propagation
y_sigmoid_tf = sigmoid(x)
y_tanh_tf = tanh(x)
y_relu_tf = relu(x)


# forward propagation(manual)
y_sigmoid_man = 1 / (1 + exp(-x))
y_tanh_man = (exp(x) - exp(-x)) / (exp(x) + exp(-x))
y_relu_man = maximum(0, x)

print("x: {}\n{}".format(x.shape, x.numpy()))
print("Sigmoid(Tensorflow): {}\n{}\n".format(y_sigmoid_tf.shape, y_sigmoid_tf.numpy()))
print("Sigmoid(man): {}\n{}\n".format(y_sigmoid_man.shape, y_sigmoid_man.numpy()))

print("Tanh(Tensorflow): {}\n{}\n".format(y_tanh_tf.shape, y_tanh_tf.numpy()))
print("Tanh(man): {}\n{}\n".format(y_tanh_man.shape, y_tanh_man.numpy()))

print("ReLu(Tensorflow): {}\n{}\n".format(y_relu_tf.shape, y_relu_tf.numpy()))
print("ReLu(man): {}\n{}\n".format(y_relu_man.shape, y_relu_man.numpy()))





x: (1, 5)
[[-1.3544159   0.7045493   0.03666191  0.86918795  0.43842277]]
Sigmoid(Tensorflow): (1, 5)
[[0.20514935 0.6691957  0.5091645  0.70457673 0.6078832 ]]

Sigmoid(man): (1, 5)
[[0.20514935 0.6691957  0.5091645  0.70457673 0.6078832 ]]

Tanh(Tensorflow): (1, 5)
[[-0.87509155  0.6072475   0.03664547  0.7009613   0.41233623]]

Tanh(man): (1, 5)
[[-0.8750916   0.60724753  0.03664549  0.7009614   0.41233623]]

ReLu(Tensorflow): (1, 5)
[[0.         0.7045493  0.03666191 0.86918795 0.43842277]]

ReLu(man): (1, 5)
[[0.         0.7045493  0.03666191 0.86918795 0.43842277]]



### Code. 1-3-2: Activation in Dense Layer

In [20]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

x = tf.random.normal(shape=(1, 5)) # input setting

# imp. artificial neurons
dense_sigmoid = Dense(units = 1, activation = 'sigmoid')
dense_tanh = Dense(units = 1, activation = 'tanh')
dense_relu = Dense(units = 1, activation = 'relu')

# forward propagation
y_sigmoid = dense_sigmoid(x)
y_tanh = dense_tanh(x)
y_relu = dense_relu(x)


# forward propagation(tensorflow)
print("AN with Sigmoid: {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))

print("AN with Tanh: {}\n{}".format(y_tanh.shape, y_tanh.numpy()))

print("AN with ReLU: {}\n{}".format(y_relu.shape, y_relu.numpy()))

# forward propagation(manual)
print("\n============================================================\n")

W, B = dense_sigmoid.get_weights()
z = tf.linalg.matmul(x, W) + B
a = 1 / (1 + exp(-z))

print("Activation value(Tensorflow): {}\n{}".format(y_sigmoid.shape, y_sigmoid.numpy()))
print("Activation value(manual): {}\n{}".format(a.shape, a.numpy()))



AN with Sigmoid: (1, 1)
[[0.6933557]]
AN with Tanh: (1, 1)
[[-0.9479435]]
AN with ReLU: (1, 1)
[[0.]]


Activation value(Tensorflow): (1, 1)
[[0.6933557]]
Activation value(manual): (1, 1)
[[0.6933557]]


### Code. 1-4-1: Artificial Neurons

In [37]:
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.math import exp, maximum

# activation = 'sigmoid'
# activation = 'tanh'
activation = 'relu'

x = tf.random.uniform(shape=(1, 10)) # input setting

dense = Dense(units = 1, activation=activation) # imp. an affine + activation

y_tf = dense(x)
W, B = dense.get_weights()

# calculate activation value manually
y_man = tf.linalg.matmul(x, W) + B
if activation == 'sigmoid':
    y_man = 1 / (1 + exp(-y_man))

elif activation == 'tanh':
    y_man = (exp(y_man) - exp(-y_man)) / (exp(y_man) + exp(-y_man))

elif activation == 'relu':
    y_man = maximum(0, y_man)
    
print('Activation: ', activation)
print('y_tf: {}\n{}\n'.format(y_tf.shape, y_tf.numpy()))
print('y_man: {}\n{}\n'.format(y_man.shape, y_man.numpy()))



Activation:  relu
y_tf: (1, 1)
[[0.4924237]]

y_man: (1, 1)
[[0.4924237]]



# 1-5 : Minibatches

### Code. 1-5-1: Shapes of Dense Layers

In [49]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10 # set input parmas
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch
print(x.shape)

dense = Dense(units = 1, activation = 'relu') # imp. an AN
y = dense(x) # forward propagation

W, B = dense.get_weights() # get weight/bias

# print result
print("Shape of x: {}".format(x.shape))
print("Shape of W: {}".format(W.shape))
print("Shape of B: {}".format(B.shape))






(8, 10)
Shape of x: (8, 10)
Shape of W: (10, 1)
Shape of B: (1,)


### Code. 1-5-2: Output Calculations

In [51]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 3, 4 # set input parmas
x = tf.random.normal(shape=(N, n_feature)) # generate minibatch

dense = Dense(units = 1, activation = 'sigmoid')
y_tf = dense(x)
 
W, B = dense.get_weights()

y_man = tf.linalg.matmul(x, W) + B
y_man = 1 / (1 + exp(-y_man))

print("W shape: \n", W.shape)
print("Output(TF): \n",y_tf.numpy())
print("Output(MAN): \n",y_man.numpy())


W shape: 
 (4, 1)
Output(TF): 
 [[0.25007227]
 [0.5523918 ]
 [0.8002374 ]]
Output(MAN): 
 [[0.25007227]
 [0.5523918 ]
 [0.8002374 ]]
