# 2-1: Dense Layers

### Code.2-1-1: Shapes of Dense Layers

In [4]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 8, 10

X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units=n_neuron, activation='sigmoid')
Y = dense(X)

W, B = dense.get_weights()

print("===== Input/Weight/Bias =====")
print("X: ", X.shape)
print("W: ", W.shape)
print("B: ", B.shape)
print("Y: ", Y.shape)


===== Input/Weight/Bias =====
X:  (8, 10)
W:  (10, 3)
B:  (3,)
Y:  (8, 3)


### Code.2-1-2: Output Calculations

In [15]:
import numpy as np
import tensorflow as tf
from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neuron = 3
dense = Dense(units = n_neuron, activation = 'sigmoid')
Y_tf = dense(X)

W, B = dense.get_weights()
print("Y(Tensorflow): \n", Y_tf.numpy())

# calc with matrix multiplication
Z = matmul(X, W) + B
Y_man_matmul = 1 / (1 + exp(-Z))
print("Y(with matrix multiplication: \n)", Y_man_matmul.numpy())

# print('W',W)
print('X shape: ', X.shape)
# calc with dot products
Y_man_vec = np.zeros(shape=(N, n_neuron))
# print(Y_man_vec)
for x_idx in range(N):
    x = X[x_idx, :]
    # print('x: ', x)
    
    for nu_idx in range(n_neuron):
        w, b = W[:, nu_idx], B[nu_idx]
        # print('w: ', w)
        z = tf.reduce_sum(x * w) + b
        a = 1 / (1 + np.exp(-z))
        Y_man_vec[x_idx, nu_idx] = a

print("Y(with dot products:) \n", Y_man_vec)


Y(Tensorflow): 
 [[0.41390273 0.20940256 0.37677005]
 [0.83916765 0.85222584 0.47000486]
 [0.13364716 0.20498145 0.6551169 ]
 [0.25150403 0.2082321  0.55692154]]
Y(with matrix multiplication: 
) [[0.41390273 0.20940256 0.37677005]
 [0.83916765 0.85222584 0.47000486]
 [0.13364716 0.20498145 0.6551169 ]
 [0.25150403 0.2082321  0.55692154]]
X shape:  (4, 10)
x:  tf.Tensor(
[-1.3544159   0.7045493   0.03666191  0.86918795  0.43842277 -0.53439844
 -0.07710292  1.5658046  -0.1012345  -0.2744975 ], shape=(10,), dtype=float32)
x:  tf.Tensor(
[ 1.420466    1.2609465  -0.4364091  -1.963399   -0.06452482 -1.056841
  1.0019135   0.6735137   0.06987705 -1.4077919 ], shape=(10,), dtype=float32)
x:  tf.Tensor(
[ 1.0278524   0.2797411  -0.01347954  1.8451811   0.9706112  -1.0242516
 -0.6544423  -0.29738778 -1.3240397   0.28785658], shape=(10,), dtype=float32)
x:  tf.Tensor(
[-0.87579006 -0.08856997  0.6921164   0.842157   -0.06378508  0.9280078
 -0.6039788  -0.17669262  0.04221032  0.29037958], shape=

# 2-2: Cascaded Dense Layers

### Code.2-2-1: Shape of Cascaded Dense Layers

In [34]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [3, 5]
dense1 = Dense(units=n_neurons[0], activation='sigmoid')
dense2 = Dense(units=n_neurons[1], activation='sigmoid')

# forward propagation
A1 = dense1(X)
Y = dense2(A1)

# get weight/bias
W1, B1 = dense1.get_weights()
W2, B2 = dense2.get_weights()

print("X: {}\n".format(X.shape))
print("W1: ", W1.shape)
print("B1: ", B1.shape)

print("A1: {}\n".format(A1.shape))

print("W2: ", W2.shape)
print("B2: ", B2.shape)

print("Y: {}\n".format(Y.shape))

X: (4, 10)

W1:  (10, 3)
B1:  (3,)
A1: (4, 3)

W2:  (3, 5)
B2:  (5,)
Y: (4, 5)



### Code.2-2-2: Dense Layers with Python List

In [40]:
import tensorflow as tf
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))

n_neurons = [10, 20, 30, 40, 50, 60, 70, 80, 90]

dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='relu')
    dense_layers.append(dense)
    
print(len(dense_layers))
print("Input: ", X.shape)
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    print("After dense layer ", dense_idx+1);
    print(X.shape, '\n')


9
Input:  (4, 10)
After dense layer  1
(4, 10) 

After dense layer  2
(4, 20) 

After dense layer  3
(4, 30) 

After dense layer  4
(4, 40) 

After dense layer  5
(4, 50) 

After dense layer  6
(4, 60) 

After dense layer  7
(4, 70) 

After dense layer  8
(4, 80) 

After dense layer  9
(4, 90) 



### code.2-2-3: Output Calculators

In [48]:
import tensorflow as tf
from tensorflow.math import exp
from tensorflow.linalg import matmul
from tensorflow.keras.layers import Dense

N, n_feature = 4, 10
X = tf.random.normal(shape=(N, n_feature))
X_cp = tf.identity(X)

n_neurons = [3, 4, 5]

dense_layers = list()
for n_neuron in n_neurons:
    dense = Dense(units=n_neuron, activation='sigmoid')
    dense_layers.append(dense)
    

# forward propagation(Tensorflow)
W, B = list(), list()
for dense_idx, dense in enumerate(dense_layers):
    X = dense(X)
    w, b = dense.get_weights()
    W.append(w)
    B.append(b)
print("Y(Tensorflow): \n", X.numpy())


# forward propagation(Manual)
for layer_idx in range(len(n_neurons)):
    w, b = W[layer_idx], B[layer_idx]

    X_cp = matmul(X_cp, w) + b
    X_cp = 1 / (1 + exp(-X_cp))
print("Y(Manual): \n", X_cp.numpy())



Y(Tensorflow): 
 [[0.49491575 0.44732755 0.4787393  0.44284943 0.5818738 ]
 [0.5008767  0.4300911  0.46937752 0.4436389  0.5907325 ]
 [0.49400163 0.44131932 0.47426486 0.44184828 0.5875968 ]
 [0.49765313 0.45043254 0.4806611  0.4473359  0.57554144]]
Y(Manual): 
 [[0.49491575 0.44732755 0.4787393  0.44284943 0.5818738 ]
 [0.5008767  0.4300911  0.46937752 0.4436389  0.5907325 ]
 [0.49400163 0.44131932 0.47426486 0.44184828 0.5875968 ]
 [0.49765313 0.45043254 0.4806611  0.4473359  0.57554144]]
