# 6-1: Max/Avg Pooling

### Code.6-1-1: Max Pooling

In [9]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling1D

Length, pooling_size, stride = 10, 2, 1
                        # 데이터 갯수     # 열
x = tf.random.normal(shape = (1, Length, 1))
                                 # 길이(행))
pool_max = MaxPooling1D(pool_size = pooling_size, strides = stride)
pooled_max = pool_max(x)

print("x:{}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max.numpy().flatten()))


x = x.numpy().flatten()
pooled_max_man = np.zeros((Length - pooling_size + 1, ))

for i in range(Length - pooling_size + 1):
    window = x[i:i+pooling_size]
    pooled_max_man[i] = np.max(window)

print("pooled_max(Manual): {}\n{}".format(pooled_max.shape,
                                              pooled_max_man))



x:(1, 10, 1)
[-1.3544159   0.7045493   0.03666191  0.86918795  0.43842277 -0.53439844
 -0.07710292  1.5658046  -0.1012345  -0.2744975 ]
pooled_max(Tensorflow): (1, 9, 1)
[ 0.7045493   0.7045493   0.86918795  0.86918795  0.43842277 -0.07710292
  1.5658046   1.5658046  -0.1012345 ]
pooled_max(Manual): (1, 9, 1)
[ 0.70454931  0.70454931  0.86918795  0.86918795  0.43842277 -0.07710292
  1.5658046   1.5658046  -0.1012345 ]


### Code.6-1-2: Average Pooling

In [17]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import AveragePooling1D

Length, pooling_size, stride = 10, 2, 1
                        # 데이터 갯수     #(열) 
x = tf.random.normal(shape = (1, Length, 1))   
                                 # 길이(행)

pool_avg = AveragePooling1D(pool_size = pooling_size, strides = stride)
pooled_avg = pool_avg(x)

print("x:{}\n{}".format(x.shape, x.numpy().flatten()))
print("pooled_avg(Tensorflow): {}\n{}".format(pooled_avg.shape,
                                              pooled_avg.numpy().flatten()))


x = x.numpy().flatten()
pooled_avg_man = np.zeros((Length - pooling_size + 1, ))

for i in range(Length - pooling_size + 1):
    window = x[i:i+pooling_size]
    pooled_avg_man[i] = np.mean(window)

print("pooled_avg(Manual): {}\n{}".format(pooled_avg_man.shape,
                                              pooled_avg_man))



tf.Tensor(
[[[-1.3544159 ]
  [ 0.7045493 ]
  [ 0.03666191]
  [ 0.86918795]
  [ 0.43842277]
  [-0.53439844]
  [-0.07710292]
  [ 1.5658046 ]
  [-0.1012345 ]
  [-0.2744975 ]]], shape=(1, 10, 1), dtype=float32)
x:(1, 10, 1)
[-1.3544159   0.7045493   0.03666191  0.86918795  0.43842277 -0.53439844
 -0.07710292  1.5658046  -0.1012345  -0.2744975 ]
pooled_avg(Tensorflow): (1, 9, 1)
[-0.3249333   0.37060562  0.45292494  0.6538054  -0.04798783 -0.30575067
  0.74435085  0.732285   -0.187866  ]
pooled_avg(Manual): (9,)
[-0.32493329  0.37060562  0.45292494  0.65380538 -0.04798783 -0.30575067
  0.74435085  0.73228502 -0.187866  ]


# 6-2: 2D Max/Avg Pooling

### Code.6-2-1: 2D Max Pooling

In [26]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1

pooling_size, stride = 2, 1

x = tf.random.normal(shape = (N, n_H, n_W, n_C))
pool_max = MaxPooling2D(pool_size = pooling_size, strides = stride)
pooled_max = pool_max(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_max.shape,
                                              pooled_max.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_max_man = np.zeros(shape = (n_H - pooling_size + 1, n_W - pooling_size + 1))

for i in range(n_H - pooling_size + 1):
    for j in range(n_W - pooling_size + 1):
        window = x[i:i+pooling_size, j:j+pooling_size]
        pooled_max_man[i, j] = np.max(window)

print("pooled_max(Manual): {}\n{}".format(pooled_max_man.shape,
                                              pooled_max_man))

x: (1, 5, 5, 1)
[[-1.3544159   0.7045493   0.03666191  0.86918795  0.43842277]
 [-0.53439844 -0.07710292  1.5658046  -0.1012345  -0.2744975 ]
 [ 1.420466    1.2609465  -0.4364091  -1.963399   -0.06452482]
 [-1.056841    1.0019135   0.6735137   0.06987705 -1.4077919 ]
 [ 1.0278524   0.2797411  -0.01347954  1.8451811   0.9706112 ]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[ 0.7045493   1.5658046   1.5658046   0.86918795]
 [ 1.420466    1.5658046   1.5658046  -0.06452482]
 [ 1.420466    1.2609465   0.6735137   0.06987705]
 [ 1.0278524   1.0019135   1.8451811   1.8451811 ]]
pooled_max(Manual): (4, 4)
[[ 0.70454931  1.5658046   1.5658046   0.86918795]
 [ 1.42046595  1.5658046   1.5658046  -0.06452482]
 [ 1.42046595  1.26094651  0.67351371  0.06987705]
 [ 1.02785242  1.00191355  1.84518111  1.84518111]]


### Code.6-2-2: 2D Average Pooling

In [27]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import AveragePooling2D

N, n_H, n_W, n_C = 1, 5, 5, 1

pooling_size, stride = 2, 1

x = tf.random.normal(shape = (N, n_H, n_W, n_C))
pool_avg = AveragePooling2D(pool_size = pooling_size, strides = stride)
pooled_avg = pool_avg(x)

print("x: {}\n{}".format(x.shape, x.numpy().squeeze()))
print("pooled_max(Tensorflow): {}\n{}".format(pooled_avg.shape,
                                              pooled_avg.numpy().squeeze()))

x = x.numpy().squeeze()
pooled_avg_man = np.zeros(shape = (n_H - pooling_size + 1, n_W - pooling_size + 1))

for i in range(n_H - pooling_size + 1):
    for j in range(n_W - pooling_size + 1):
        window = x[i:i+pooling_size, j:j+pooling_size]
        pooled_avg_man[i, j] = np.mean(window)

print("pooled_max(Manual): {}\n{}".format(pooled_avg_man.shape,
                                              pooled_avg_man))

x: (1, 5, 5, 1)
[[-1.3544159   0.7045493   0.03666191  0.86918795  0.43842277]
 [-0.53439844 -0.07710292  1.5658046  -0.1012345  -0.2744975 ]
 [ 1.420466    1.2609465  -0.4364091  -1.963399   -0.06452482]
 [-1.056841    1.0019135   0.6735137   0.06987705 -1.4077919 ]
 [ 1.0278524   0.2797411  -0.01347954  1.8451811   0.9706112 ]]
pooled_max(Tensorflow): (1, 4, 4, 1)
[[-0.31534198  0.55747825  0.592605    0.2329697 ]
 [ 0.51747775  0.5783098  -0.23380953 -0.600914  ]
 [ 0.6566212   0.6249912  -0.41410437 -0.84145963]
 [ 0.3131665   0.48542216  0.6437731   0.36946937]]
pooled_max(Manual): (4, 4)
[[-0.31534198  0.55747825  0.59260499  0.2329697 ]
 [ 0.51747775  0.57830977 -0.23380953 -0.600914  ]
 [ 0.65662122  0.62499118 -0.41410437 -0.84145963]
 [ 0.3131665   0.48542216  0.64377308  0.36946937]]
