# 6-3: 3D Max/Avg Pooling

### Code.6-3-1: 3D Max Pooling

In [4]:
import math
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

N, n_H, n_W, n_C = 1, 5, 5, 3
f, s = 2, 2

x = tf.random.normal(shape = (N, n_H, n_W, n_C))
# print("x: {}\n{}".format(x.shape, np.transpose(x.numpy().squeeze(), (2, 0, 1))))

pool_max = MaxPooling2D(pool_size = f, strides = s)
pooled_max = pool_max(x)

pooled_max_t = np.transpose(pooled_max.numpy().squeeze(), (2, 0, 1))
print("pooled_max(Tensorflow: {}\n{})".format(pooled_max.shape,
                                              pooled_max_t))

# [[[0.86918795 0.9706112 ]     R
#   [0.842157   0.60545963]]

#  [[1.0019135  1.5658046 ]     G 
#   [0.28291693 0.37944326]]

#  [[1.0278524  1.8451811 ]     B
#   [1.2132235  0.80458266]]])

#### 
x = x.numpy().squeeze()
n_H_ = math.floor((n_H - f) / s + 1)    # floor 함수는 실수를 입력하면내림하여 정수를 반환하는 함수
n_W_ = math.floor((n_W - f) / s + 1)
pooled_max_man = np.zeros(shape = (n_H_, n_W_, n_C))

for c in range(n_C):
    c_image = x[:, :, c]

    h_ = 0
    for h in range(0, n_H - f + 1, s):
        w_ = 0
        for w in range(0, n_W - f + 1, s):
            window = c_image[h:h+f, w:w+f]
            pooled_max_man[h_, w_, c] = np.max(window)

            w_ += 1
        h_ += 1

pooled_max_t = np.transpose(pooled_max_man, (2, 0, 1))
print("Pooled_max(Manual): {}\n{}".format(pooled_max_man.shape,
                                          pooled_max_t))






pooled_max(Tensorflow: (1, 2, 2, 3)
[[[0.86918795 0.9706112 ]
  [0.842157   0.60545963]]

 [[1.0019135  1.5658046 ]
  [0.28291693 0.37944326]]

 [[1.0278524  1.8451811 ]
  [1.2132235  0.80458266]]])
Pooled_max(Manual): (2, 2, 3)
[[[0.86918795 0.97061121]
  [0.84215701 0.60545963]]

 [[1.00191355 1.5658046 ]
  [0.28291693 0.37944326]]

 [[1.02785242 1.84518111]
  [1.21322346 0.80458266]]]


# 6-4: Padding

### Code.6-4-1: ZeroPadding2D Layer

In [6]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.layers import ZeroPadding2D

images = tf.random.normal(shape = (1, 3, 3, 3))
print(images.shape)
print(np.transpose(images.numpy().squeeze(), (2, 0, 1)))

# [[[-1.3544159   0.86918795 -0.07710292]       R
#   [-0.2744975  -0.4364091  -1.056841  ]
#   [ 0.06987705  0.2797411   0.9706112 ]]

#  [[ 0.7045493   0.43842277  1.5658046 ]       G
#   [ 1.420466   -1.963399    1.0019135 ]
#   [-1.4077919  -0.01347954 -1.0242516 ]]

#  [[ 0.03666191 -0.53439844 -0.1012345 ]       B
#   [ 1.2609465  -0.06452482  0.6735137 ]
#   [ 1.0278524   1.8451811  -0.6544423 ]]]




zero_padding = ZeroPadding2D(padding = 1)
y = zero_padding(images)
print(y.shape)
print(np.transpose(y.numpy().squeeze(), (2, 0 ,1)))

# [[[ 0.          0.          0.          0.          0.        ]       
#   [ 0.         -1.3544159   0.86918795 -0.07710292  0.        ]       R
#   [ 0.         -0.2744975  -0.4364091  -1.056841    0.        ]
#   [ 0.          0.06987705  0.2797411   0.9706112   0.        ]
#   [ 0.          0.          0.          0.          0.        ]]

#  [[ 0.          0.          0.          0.          0.        ]
#   [ 0.          0.7045493   0.43842277  1.5658046   0.        ]       G
#   [ 0.          1.420466   -1.963399    1.0019135   0.        ]
#   [ 0.         -1.4077919  -0.01347954 -1.0242516   0.        ]
#   [ 0.          0.          0.          0.          0.        ]]

#  [[ 0.          0.          0.          0.          0.        ]
#   [ 0.          0.03666191 -0.53439844 -0.1012345   0.        ]       B
#   [ 0.          1.2609465  -0.06452482  0.6735137   0.        ]
#   [ 0.          1.0278524   1.8451811  -0.6544423   0.        ]
#   [ 0.          0.          0.          0.          0.        ]]]

(1, 3, 3, 3)
[[[-1.3544159   0.86918795 -0.07710292]
  [-0.2744975  -0.4364091  -1.056841  ]
  [ 0.06987705  0.2797411   0.9706112 ]]

 [[ 0.7045493   0.43842277  1.5658046 ]
  [ 1.420466   -1.963399    1.0019135 ]
  [-1.4077919  -0.01347954 -1.0242516 ]]

 [[ 0.03666191 -0.53439844 -0.1012345 ]
  [ 1.2609465  -0.06452482  0.6735137 ]
  [ 1.0278524   1.8451811  -0.6544423 ]]]
(1, 5, 5, 3)
[[[ 0.          0.          0.          0.          0.        ]
  [ 0.         -1.3544159   0.86918795 -0.07710292  0.        ]
  [ 0.         -0.2744975  -0.4364091  -1.056841    0.        ]
  [ 0.          0.06987705  0.2797411   0.9706112   0.        ]
  [ 0.          0.          0.          0.          0.        ]]

 [[ 0.          0.          0.          0.          0.        ]
  [ 0.          0.7045493   0.43842277  1.5658046   0.        ]
  [ 0.          1.420466   -1.963399    1.0019135   0.        ]
  [ 0.         -1.4077919  -0.01347954 -1.0242516   0.        ]
  [ 0.          0.          0.

### Code.6-4-2: Zero Padding with Conv2D Layers

In [7]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape = (1, 28, 28, 3))

# conv layer 에서는 same 또는 valid padding 을 주로 사용 
# same padding 은 윈도우가 움직일 때 코너 케이스를 계산해줘서 사이즈가 줄어들지 않도록 패딩을 자동으로 해준다.
conv = Conv2D(filters = 1, kernel_size = 3, padding = 'same') 
y = conv(images)
print(y.shape) 

(1, 28, 28, 1)


# 6-5: Strides

### Code.6-5-1: Strides in Conv2D Layers

In [8]:
import tensorflow as tf
from tensorflow.keras.layers import Conv2D

images = tf.random.normal(shape = (1, 28, 28, 3))
conv = Conv2D(filters = 1, kernel_size = 3, padding = 'valid', strides = 2)
y = conv(images)

print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 1)


### Code.6-5-2: Strides in Pooling Layers

In [9]:
import tensorflow as tf
from tensorflow.keras.layers import MaxPooling2D

images = tf.random.normal(shape = (1, 28, 28, 3))
conv = MaxPooling2D(pool_size = 3, strides = 2)
y = conv(images)

print(images.shape)
print(y.shape)

(1, 28, 28, 3)
(1, 13, 13, 3)
