In [1]:
from sklearn.preprocessing import LabelEncoder

fruits = ['사과', '블루베리', '바나나', '귤', '블루베리', '바나나', '바나나', '사과']

label_encoder = LabelEncoder()

label_encoded = label_encoder.fit_transform(fruits)
print(label_encoded)

[3 2 1 0 2 1 1 3]


In [6]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

fruits = ['사과', '블루베리', '바나나', '귤', '블루베리', '바나나', '바나나', '사과']

label_encoder = LabelEncoder()
onehot_encoder = OneHotEncoder()

label_encoded = label_encoder.fit_transform(fruits)
onehot_encoded = onehot_encoder.fit_transform(label_encoded.reshape(-1, 1))

print(onehot_encoded.toarray())

print(onehot_encoded.shape)


[[0. 0. 0. 1.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 1. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 0. 1.]]
(8, 4)


In [7]:
import pandas as pd

pd.get_dummies(fruits)

,귤,바나나,블루베리,사과
0,False,False,False,True
1,False,False,True,False
2,False,True,False,False
3,True,False,False,False
4,False,False,True,False
5,False,True,False,False
6,False,True,False,False
7,False,False,False,True
